type TerminologiesProps = {
  [key: string]: {
    title: string;
    sub: string;
    desc: string;
    img: string;
    voice: string;
  }[];
}

export const Terminologies: TerminologiesProps = {
  Aa: [
    {
      title: "Abaká",
      sub: "pangngalan",
      desc: "Isang halamang hemp o napagkukunan ng himayma na berde ang mga dahon na kawangis ng dahon ng saging. Ito ay ginagamit bilang pantali at panahi sa walis tambo.",
      img: "/images/abaka.jpg",
      voice: "/audio/ABAKA .m4a",
    },
    {
      title: "Alámbré",
      sub: "pangngalan",
      desc: "Manipis na piraso ng bakal na ginagamit sa pagbibigkis ng tambo.",
      img: "/images/alambre.jpg",
      voice: "/audio/ALAMBRE.m4a",
    },
  ],
  Bb: [
    {
      title: "Baréna",
      sub: "pangngalan",
      desc: "Kagamitang pambutas sa itaas na bahagi ng tangkay na nilalagyan ng tali.",
      img: "/images/barena.jpg",
      voice: "/audio/BARENA.m4a",
    },
    {
      title: "Berdeng Tambo",
      sub: "pang-uri",
      desc: "Isang uri ng tambo na may berdeng kulay kapag sariwa.",
      img: "/images/berdeng.jpg",
      voice: "/audio/BERDENG TAMBO .m4a",
    },
    {
      title: "Bílàd",
      sub: "pandiwa",
      desc: "Proseso ng pagpapatuyo ng tambo upang mapanatili ang tibay nito.",
      img: "",
      voice: "/audio/BILAD .m4a",
    },
    {
      title: "Binanig na Walis Tambo",
      sub: "pangngalan",
      desc: 'Isang uri ng walis tambo na may masikip at patag na pagkakatali, kaya ito ay parang "banig" sa itsura.',
      img: "/images/binanig.jpg",
      voice: "/audio/BINANIG NA WALIS TAMBO.m4a",
    },
    {
      title: "Binóngbong",
      sub: "pangngalan",
      desc: "Isang uri ng walis tambo na may makapal at matibay na tangkay.",
      img: "",
      voice: "/audio/BINONGBONG.m4a",
    },
    {
      title: "Blówer",
      sub: "pangngalan",
      desc: "Elektronikong kagamitan na ginagamit sa pagpapadikit ng tatak ng walis tambo sa tangkay nito.",
      img: "/images/blower.jpg",
      voice: "/audio/BLOWER.m4a",
    },
    {
      title: "Bonglíw",
      sub: "pangngalan",
      desc: "Isang uri ng kahoy na ginagamit bilang tangkay ng walis tambo.",
      img: "/images/bongliw.jpg",
      voice: "/audio/BONGLIW.m4a",
    },
    {
      title: "Bulaklak ng Tambo",
      sub: "pangngalan",
      desc: "Kulay puting bahagi ng tambo bago ito anihin.",
      img: "",
      voice: "/audio/BULAKLAK NG TAMBO.m4a",
    },
  ],
  Dd: [
    {
      title: "Dilaw na Tambo",
      sub: "pang-uri",
      desc: "Uri ng tambo na may makinang at ginintuang kulay.",
      img: "",
      voice: "/audio/DILAW NA TAMBO .m4a",
    },
    {
      title: "Dryér",
      sub: "pangngalan",
      desc: "Kagamitang ginagamit sa mas mabilis na pagpapatuyo ng tambo.",
      img: "",
      voice: "/audio/DRYER.m4a",
    },
  ],
  Gg: [
    {
      title: "Gahô",
      sub: "pangngalan",
      desc: "Isang uri ng ligaw na damo na namumulaklak ng puti at may mataas na tangkad. Bagamat naiiba sa tambo, maaari rin itong gamitin sa paggawa ng walis.",
      img: "",
      voice: "/audio/GAHO.m4a",
    },
    {
      title: "Gákod",
      sub: "pangngalan",
      desc: "Inilalagay sa itaas na bahagi ng tangkay ng tambo upang mapanatili ang ayos nito.",
      img: "/images/gakod.jpg",
      voice: "/audio/GAKOD.m4a",
    },
    {
      title: "Grímpa",
      sub: "pangngalan",
      desc: "Matulis na bahagi ng dahon ng tambo.",
      img: "",
      voice: "/audio/GRIMPA.m4a",
    },
    {
      title: "Gunting",
      sub: "pangngalan",
      desc: "Gamit sa pagputol ng sinulid, plastic rattan, o tambo",
      img: "/images/gunting.jpg",
      voice: "/audio/GUNTING.m4a",
    },
  ],
  Hh: [
    {
      title: "Híkít",
      sub: "pangngalan",
      desc: "Mahigpit na pagtatali ng walis tambo.",
      img: "",
      voice: "/audio/IPIT.m4a",
    },
  ],
  Ii: [
    {
      title: "Ípit",
      sub: "pangngalan",
      desc: "Gamit upang pansamantalang ipitin ang tambo habang tinatahi.",
      img: "/images/ipit.jpg",
      voice: "/audio/IPIT.m4a",
    },
  ],
  Jj: [
    {
      title: "Júmbo",
      sub: "pang-uri",
      desc: "Walis tambo na may makapal at matibay na pagkakagawa.",
      img: "",
      voice: "/audio/JUMBO.m4a",
    },
  ],
  Kk: [
    {
      title: "Karayóm",
      sub: "pangngalan",
      desc: "Matulis na bakal na ginagamit sa pagtatahi ng walis tambo.",
      img: "/images/karayom.jpg",
      voice: "/audio/KARAYOM.m4a",
    },
    {
      title: "Katám",
      sub: "pangngalan",
      desc: "Kagamitang pampakinis ng tangkay ng walis tambo.",
      img: "/images/katam.jpg",
      voice: "/audio/KATAM.m4a",
    },
    {
      title: "Kawád",
      sub: "pangngalan",
      desc: "Manipis na bakal na pantali sa paggawa ng walis tambo.",
      img: "",
      voice: "/audio/KAWAD.m4a",
    },
  ],
  Ll: [
    {
      title: "Lilak na Tambo",
      sub: "pang-uri",
      desc: "Unang tumutubong halaman ng tambo, may kulay lila.",
      img: "/images/lilak.jpg",
      voice: "/audio/LILAK NA TAMBO.m4a",
    },
  ],
  Mm: [
    {
      title: "Martílyo",
      sub: "pangngalan",
      desc: "Gamit na ginagamit sa pagpukpok ng pako.",
      img: "/images/martilyo.jpg",
      voice: "/audio/MARTILYO.m4a",
    },
  ],
  Nn: [
    {
      title: "Nýlon",
      sub: "pangngalan",
      desc: "Matibay na sintetikong pantali sa walis tambo.",
      img: "/images/nylon.jpg",
      voice: "/audio/NYLON.m4a",
    },
  ],
  Oo: [
    {
      title: "Ordináryo",
      sub: "pang-uri",
      desc: "Manipis at karaniwang ginagamit na walis tambo.",
      img: "",
      voice: "/audio/ORDINARYO.m4a",
    },
  ],
  Pp: [
    {
      title: "Pag-aagón",
      sub: "pandiwa",
      desc: "Ang buong proseso ng maingat na pagpapatuyo ng tambo gamit ang mahinang apoy.",
      img: "",
      voice: "/audio/PAG-AAGON .m4a",
    },
    {
      title: "Pag-ání",
      sub: "pandiwa",
      desc: "Proseso ng pagputol ng tambo upang magamit sa paggawa ng walis",
      img: "",
      voice: "/audio/PAG-ANI.m4a",
    },
    {
      title: "Pagbubúka",
      sub: "pandiwa",
      desc: "Ginagamitan ng sipit o ipit upang maayos ang pagtatahi ng walis tambo.",
      img: "",
      voice: "/audio/PAGBUBUKA.m4a",
    },
    {
      title: "Paggagápas",
      sub: "pandiwa",
      desc: "Proseso ng pagputol o pag-aani ng tambo",
      img: "",
      voice: "/audio/PAGGAGAPAS.m4a",
    },
    {
      title: "Pagdídikit",
      sub: "pandiwa",
      desc: "Paraan ng pagsasama-sama ng mga hibla ng tambo gamit ang alambre o kawad",
      img: "",
      voice: "/audio/PAGDIDIKIT.m4a",
    },
    {
      title: "Pagpápatong",
      sub: "pandiwa",
      desc: "Pagtatambak ng bagong aning tambo upang mapanatili ang kalidad nito bago iproseso.",
      img: "",
      voice: "/audio/PAGPAPATONG.m4a",
    },
    {
      title: "Pakó",
      sub: "pangngalan",
      desc: "Maliit na piraso ng bakal na ginagamit upang hindi bumitaw ang mga bahagi ng walis tambo.",
      img: "",
      voice: "/audio/PAKO.m4a",
    },
    {
      title: "Paghíhimay",
      sub: "pandiwa",
      desc: "Paraan ng pagtatanggal ng mga sanga sa halaman ng tambo.",
      img: "",
      voice: "/audio/PAGHIHIMAY.m4a",
    },
    {
      title: "Paghuhúlmà",
      sub: "pandiwa",
      desc: "Pagbibigay ng tamang hugis sa walis tambo bago ito tahiin.",
      img: "",
      voice: "/audio/PAGHUHULMA.m4a",
    },
    {
      title: "Pag-iimbák",
      sub: "pandiwa",
      desc: "Pansamantalang pagtatago ng bagong aning tambo upang hindi ito masira.",
      img: "",
      voice: "/audio/PAG-IIMBAK.m4a",
    },
    {
      title: "Pag-iipít",
      sub: "pandiwa",
      desc: "Pansamantalang paghawak sa tambo gamit ang ipit habang ito ay tinatahi.",
      img: "",
      voice: "/audio/PAG-IIPIT.m4a",
    },
    {
      title: "Pagkakawád",
      sub: "pandiwa",
      desc: "Proseso ng pagbibigkis ng walis tambo gamit ang kawad o alambre.",
      img: "",
      voice: "/audio/PAGKAKAWAD.m4a",
    },
    {
      title: "Pagkakatíg",
      sub: "pandiwa",
      desc: "Paglalagay ng dagdag na alambre o sinulid upang mas tumibay ang walis tambo.",
      img: "",
      voice: "/audio/PAGKAKATIG.m4a",
    },
    {
      title: "Paglalagay ng Tatak",
      sub: "pandiwa",
      desc: "Paglalagay ng pangalan ng produkto bago ito ibenta.",
      img: "",
      voice: "/audio/PAGLALAGAY NG TATAK.m4a",
    },
    {
      title: "Pángharong",
      sub: "pangngalan",
      desc: "Uri ng walis tambo na ginagamit sa pang-araw-araw na paglilinis.",
      img: "",
      voice: "/audio/PANGHARONG.m4a",
    },
    {
      title: "Pagpantáy",
      sub: "pandiwa",
      desc: "Pagputol ng dulo ng tambo upang maging pantay",
      img: "",
      voice: "/audio/PAGPANTAY.m4a",
    },
    {
      title: "Pagpapágpag",
      sub: "pandiwa",
      desc: "Pag-aalis ng mga bulaklak at dumi mula sa tambo.",
      img: "",
      voice: "/audio/PAGPAPAGPAG.m4a",
    },
    {
      title: "Pagpapakinís",
      sub: "pandiwa",
      desc: "Pagpapakinis ng tangkay gamit ang katam.",
      img: "",
      voice: "/audio/PAGPAPAKINIS.m4a",
    },
    {
      title: "Pagpapásada",
      sub: "pandiwa",
      desc: "Pagtatama ng porma ng walis tambo upang ito ay maging maayos at maganda.",
      img: "",
      voice: "/audio/PAGPAPASADA.m4a",
    },
    {
      title: "Pagpipíno",
      sub: "pandiwa",
      desc: "Proseso ng pagtatanggal ng sobrang hibla ng tambo.",
      img: "",
      voice: "/audio/PAGPIPINO.m4a",
    },
    {
      title: "Pagpapások",
      sub: "pandiwa",
      desc: "Pagsisigurong ang lahat ng hibla ng tambo ay pantay-pantay bago ito tahiin.",
      img: "",
      voice: "/audio/PAGPAPASOK.m4a",
    },
    {
      title: "Pagtátali",
      sub: "pandiwa",
      desc: "Proseso ng paghigpit ng tambo gamit ang nylon o lubid.",
      img: "",
      voice: "/audio/PAGTATALI.m4a",
    },
    {
      title: "Pagtatáhì",
      sub: "pandiwa",
      desc: "Pagsasama-sama ng tambo gamit ang plastic rattan o sinulid.",
      img: "",
      voice: "/audio/PAGTATAHI.m4a",
    },
    {
      title: "Pángtindá",
      sub: "pangngalan",
      desc: "Walis tambo na ginawa para ipagbili sa merkado.",
      img: "",
      voice: "/audio/PANGTINDA.m4a",
    },
    {
      title: "Pinínyang Walis Tambo",
      sub: "pangngalan",
      desc: "Isang klase ng walis tambo na mas pino ang hibla at mas maingat ang pagkakaayos ng hibla.",
      img: "",
      voice: "/audio/PININYANG WALIS TAMBO.m4a",
    },
    {
      title: "Plástic Rattán",
      sub: "pangngalan",
      desc: "Sintetikong hibla na ginagamit bilang sinulid sa pagtatahi.",
      img: "/images/plastic.jpg",
      voice: "/audio/PLASTIC RATTAN .m4a",
    },
  ],
  Ss: [
    {
      title: "Sáko",
      sub: "pangngalan",
      desc: "Sisidlan ng tambo upang mapanatili itong malinis at organisado, ginagamit din ito sa pagtatahi ng tambo",
      img: "/images/sako.jpg",
      voice: "/audio/SAKO.m4a",
    },
    {
      title: "Sápì",
      sub: "pangngalan",
      desc: "Pagtanggal ng mga sanga ng tambo.",
      img: "",
      voice: "/audio/SAPI.m4a",
    },
    {
      title: "Semi-special",
      sub: "pang-uri",
      desc: "Katamtamang kalidad na walis tambo.",
      img: "",
      voice: "/audio/SEMI-SPECIAL.m4a",
    },
    {
      title: "Senyoríta",
      sub: "pangngalan",
      desc: "Isang uri ng walis tambo na may kakaibang hugis na kahawig ng isang kupita o baso. Ito ay nagmula sa natatanging anyo ng walis, kung saan ang bahagi ng hibla ay mas bilugan at masikip sa taas, habang ang hawakan ay mas makitid sa ibaba",
      img: "/images/senyorita.jpg",
      voice: "/audio/SENYORITA.m4a",
    },
    {
      title: "Special",
      sub: "pang-uri",
      desc: "Pinakamagandang uri ng walis tambo na ginagawang panregalo.",
      img: "",
      voice: "/audio/SPECIAL .m4a",
    },
    {
      title: "Sundáng",
      sub: "pangngalan",
      desc: "Ginagamit na pangputol ng tangkay  ng tambo.",
      img: "/images/sundang.jpg",
      voice: "/audio/SUNDANG.m4a",
    },
  ],
  Tt: [
    {
      title: "Tambó",
      sub: "pangngalan",
      desc: "Isang halamang ginagamit sa paggawa ng walis tambo",
      img: "/images/tambo.jpg",
      voice: "/audio/TAMBO.m4a",
    },
    {
      title: "Tangkáy",
      sub: "pangngalan",
      desc: "Bahagi ng walis tambo na gawa sa bongliw o ibang matibay na kahoy.",
      img: "/images/tangkay.jpg",
      voice: "/audio/TANGKAY.m4a",
    },
    {
      title: "Tungkó",
      sub: "pangngalan",
      desc: "Isang uri ng maliit na walis tambo na ginagamit pang-alis ng mga alikabok.",
      img: "",
      voice: "/audio/TUNGKO.m4a",
    },
  ],
  Uu: [
    {
      title: "Udóg",
      sub: "pangngalan",
      desc: "Ang maliliit na bagong sibol ng tambo na tumutubo malapit sa ina nitong halaman.",
      img: "",
      voice: "/audio/UDOG.m4a",
    },
  ],
  Ww: [
    {
      title: "Walís  Tambó",
      sub: "pangngalan",
      desc: "Isang kagamitan na ginagamit sa paglilinis, gawa sa tambo at may hawakang kahoy.",
      img: "/images/walistambo.jpg",
      voice: "/audio/WALIS TAMBO.m4a",
    },
  ],
};
